/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface DiamondLoupeFacet extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DiamondLoupeFacet;
  clone(): DiamondLoupeFacet;
  methods: {
    facetAddress(
      _functionSelector: string | number[]
    ): NonPayableTransactionObject<string>;

    facetAddresses(): NonPayableTransactionObject<string[]>;

    facetFunctionSelectors(
      _facet: string
    ): NonPayableTransactionObject<string[]>;

    facets(): NonPayableTransactionObject<[string, string[]][]>;

    supportsInterface(
      _interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
