/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type DiamondCut = ContractEventLog<{
  _diamondCut: [string, string, string[]][];
  _init: string;
  _calldata: string;
  0: [string, string, string[]][];
  1: string;
  2: string;
}>;

export interface IDiamondCut extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IDiamondCut;
  clone(): IDiamondCut;
  methods: {
    diamondCut(
      _diamondCut: [string, number | string | BN, (string | number[])[]][],
      _init: string,
      _calldata: string | number[]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    DiamondCut(cb?: Callback<DiamondCut>): EventEmitter;
    DiamondCut(options?: EventOptions, cb?: Callback<DiamondCut>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "DiamondCut", cb: Callback<DiamondCut>): void;
  once(
    event: "DiamondCut",
    options: EventOptions,
    cb: Callback<DiamondCut>
  ): void;
}
