/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface MoonstreamTokenFaucet extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): MoonstreamTokenFaucet;
  clone(): MoonstreamTokenFaucet;
  methods: {
    claim(): NonPayableTransactionObject<void>;

    getFaucetAmount(): NonPayableTransactionObject<string>;

    getFaucetBlockInterval(): NonPayableTransactionObject<string>;

    getLastClaimedBlock(_address: string): NonPayableTransactionObject<string>;

    getMoonstreamTokenAddress(): NonPayableTransactionObject<string>;

    getMoonstreamTokenBalance(
      _address: string
    ): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    setFaucetAmount(
      _FAUCET_AMOUNT: number | string | BN
    ): NonPayableTransactionObject<void>;

    setFaucetBlockInterval(
      _FAUCET_BLOCK_INTERVAL: number | string | BN
    ): NonPayableTransactionObject<void>;

    setMoonstreamTokenAddress(
      _MOONSTREAM_TOKEN_ADDRESS: string
    ): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
